name: task_management_app
description: "A simple task management app"

# Do not publish this package to pub.dev
publish_to: 'none'

# Version of the app
version: 1.0.0+1

# SDK environment constraints
environment:
  sdk: ^3.6.0

# Dependencies of the app
dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  # Cupertino icons for iOS-style icons
  cupertino_icons: ^1.0.8
  # intl package for internationalization (for formatting dates)
  intl: ^0.20.1
  # Riverpod for state management
  flutter_riverpod: ^2.6.1
  # A package for rounded checkboxes
  flutter_check_box_rounded: ^3.2.3
  # SQLite database for local storage
  sqflite: ^2.4.1
  # Path package for file paths (used by sqflite)
  path: ^1.9.0
  # Logger package for logging
  logger: ^2.5.0

# Dev dependencies
dev_dependencies:
  # Flutter testing dependencies
  flutter_test:
    sdk: flutter

  # Lints for better code quality
  flutter_lints: ^5.0.0

# Flutter-specific settings
flutter:
  # Enables Material Design in the app
  uses-material-design: true

  # Add assets like images here
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # You can define custom fonts if needed
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
